# hpa-worker.yaml
{{- if and .Values.worker.enabled .Values.worker.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "my-celery-app.fullname" . }}-{{ .Values.worker.name }}-hpa
  labels:
    {{- include "my-celery-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.worker.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "my-celery-app.fullname" . }}-{{ .Values.worker.name }}
  minReplicas: {{ .Values.worker.hpa.minReplicas }}
  maxReplicas: {{ .Values.worker.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.worker.hpa.targetCPUUtilizationPercentage }}
{{- end }}