# ingress.yaml
{{- if and .Values.web.enabled .Values.web.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-celery-app.fullname" . }}-web-ingress
  labels:
    {{- include "my-celery-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.web.name }}
  {{- with .Values.web.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.web.ingress.className }}
  ingressClassName: {{ .Values.web.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.web.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.web.ingress.path }}
            pathType: {{ .Values.web.ingress.pathType }}
            backend:
              service:
                name: {{ include "my-celery-app.fullname" . }}-{{ .Values.web.name }}
                port:
                  number: {{ .Values.web.service.port }}
  {{- if .Values.web.ingress.tls }}
  tls:
    {{- toYaml .Values.web.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}