# service-web.yaml
{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-celery-app.fullname" . }}-{{ .Values.web.name }}
  labels:
    {{- include "my-celery-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.web.name }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "my-celery-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.web.name }}
{{- end }}